name: Publish VSCode Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Rust and Cargo
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install cross-compilation targets
        run: |
          rustup target add x86_64-pc-windows-gnu x86_64-apple-darwin x86_64-unknown-linux-gnu
          sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Compile executables
        run: |
          cargo build --target x86_64-pc-windows-gnu
          cargo build --target x86_64-unknown-linux-gnu

      - name: Move executables
        run: |
          sudo mkdir -p editors/vscode/server
          sudo mkdir -p editors/vscode/server/windows
          sudo mkdir -p editors/vscode/server/linux
          sudo mv target/x86_64-pc-windows-gnu/debug/asp-lsp.exe editors/vscode/server/windows/asp-lsp.exe
          sudo mv target/x86_64-unknown-linux-gnu/debug/asp-lsp editors/vscode/server/linux/asp-lsp

      - name: Install npm packages
        working-directory: editors/vscode
        run: npm install
      
      - name: Build Extension
        working-directory: editors/vscode
        run: npm run build

      - name: Install vsce for publishing
        working-directory: editors/vscode
        run: npm install -g vsce

      - name: Publish Extension
        working-directory: editors/vscode
        run: vsce publish -p ${{ secrets.VSCODE_TOKEN }}
